# Generated by Django 4.1.1 on 2023-02-01 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_news_content_news_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.CharField(default='feb,2023', max_length=250),
        ),
    ]
