# Generated by Django 4.1.1 on 2023-02-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_news_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.CharField(default='to read more...', max_length=250),
        ),
    ]
